name: C/C++ CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: submodule init
      run: git pull --recurse-submodules
    - name: objective_one
      run: cd src/objective_one && mkdir build && cd build && cmake .. && make
    - name: shared
      run: cd src/shared && mkdir build && cd build && cmake .. && make
